const data2=[
    {
        "bloodBankName":"Dhanwantari Voluntary Blood Bank & Blood Components",
        "district":"East Godavari",
        "Address":"D.No 46, 21-1, Manasa Hospital Rd, Near China Anjaneyaswamy Temple, Danavai Peta, Rajahmundry, Andhra Pradesh 533103",
        "contactNumber":08832473050,
    },
    {
        "bloodBankName":"Sri Surya Sakthi Voluntary Blood Bank",
        "district":"East Godavari",
        "Address":"Bhanugudi Junction, Srinagar, Kakinada, Andhra Pradesh 533003",
        "contactNumber":09948456739,
    },
    {
        "bloodBankName":"Vijayasri Blood Bank",
        "district":"East Godavari",
        "Address":"Behind Gandhi Park, Danavai Peta, Rajahmundry, Andhra Pradesh 533103",
        "contactNumber":08832555199,
    },
    {
        "bloodBankName":"Buddala Nagaratnam Blood Bank",
        "district":"East Godavari",
        "Address":"Nalla Gardens, Amalapuram, Andhra Pradesh 533201",
        "contactNumber":null,
    },
    {
        "bloodBankName":"A.S.N. Raju Charitable Trust Blood Bank",
        "district":"East Godavari",
        "Address":"Godavari Bund Rd, Seshayya Metta, Rajahmundry, Andhra Pradesh 533101",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Rotary Club Blood Bank",
        "district":"East Godavari",
        "Address":"Ragam Peta, Kakinada, Andhra Pradesh 533001",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Red Cross Blood Bank",
        "district":"East Godavari",
        "Address":"D.No: 8- 14-39, Red Cross Street, Gandhi Nagar, Kakinada, Andhra Pradesh 533004",
        "contactNumber":08842385800,
    },
    {
        "bloodBankName":"Indian red cross blood bank",
        "district":"East Godavari",
        "Address":"Gosha Hospital Rd, Tuni, Andhra Pradesh 533401",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Siddartha Voluntary Blood Bank",
        "district":"East Godavari",
        "Address":"H.No.8-22-11, Ground 1st Floor, Datla House, Datlavari Street, Gandhi Nagar, Kakinada, Andhra Pradesh 533004",
        "contactNumber":08842346666,
    },
    {
        "bloodBankName":"SBLOOD DONOR",
        "district":"East Godavari",
        "Address":"OPP ZPHIGH SCHOOL, Rangampeta, Andhra Pradesh 533291",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Sri surya sakthi voluntary blood bank",
        "district":"East Godavari",
        "Address":"Bhanugudi Junction, Srinagar, Kakinada, Andhra Pradesh 533003",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Smt Mattey Nagamani & Adinaryana Rotary Blood Bank",
        "district":"East Godavari",
        "Address":"Rotary Seva Bhavan Sangham, Lecturers Colony, LIC lane, Peddapuram, 533437",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Govt. Blood Bank",
        "district":"East Godavari",
        "Address":"Kakinada, Andhra Pradesh 533001",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Indian Red Cross blood bank",
        "district":"East Godavari",
        "Address":"8-10-25, Red Cross Street, Gandhi Nagar, Pratap Nagar, Kakinada, Andhra Pradesh 533004",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Babycell",
        "district":"East Godavari",
        "Address":"R Satya Ganesh, tarvanipeta, Mandapeta, Andhra Pradesh 533308",
        "contactNumber":08886222008,
    },
    {
        "bloodBankName":"VSM HEALTH CARE",
        "district":"East Godavari",
        "Address":"D.NO:34-16, 156, Tapeswaram Rd, Mandapeta, Andhra Pradesh 533308",
        "contactNumber":09392536999,
    },
    {
        "bloodBankName":"Indian Red Cross Society",
        "district":"East Godavari",
        "Address":"Pratap Nagar, Kakinada, Andhra Pradesh 533004",
        "contactNumber":7780772603,
    },
    {
        "bloodBankName":"Sahrudaya Foundation",
        "district":"East Godavari",
        "Address":"P.Gannavaram mandal, Andhra Pradesh 533240",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Needs Blood Bank",
        "district":"Guntur",
        "Address":"12- 28- 56, 1st Floor, Kothapet Main Rd, Guntur, Andhra Pradesh 522001",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Lions Vision Blood Bank",
        "district":"Guntur",
        "Address":"12-17-31, Somuvari St, Kothapeta, Guntur, Andhra Pradesh 522001",
        "contactNumber":08632336198,
    },
    {
        "bloodBankName":"SREE WELFARE SOCIETY BLOOD BANK",
        "district":"Guntur",
        "Address":"D.No:12-12, 84, Old Club Rd, Kothapeta, Guntur, Andhra Pradesh 522001",
        "contactNumber":08632217117,
    },
    {
        "bloodBankName":"G G H Blood Bank",
        "district":"Guntur",
        "Address":"1st Floor, OP Block, GGH Internal Rd, Sambasiva Pet, Guntur, Andhra Pradesh 522001",
        "contactNumber":null,
    },
    {
        "bloodBankName":"M/S. Sri Lakshmi Maternity & Surgical Nursing Home Blood Bank",
        "district":"Guntur",
        "Address":"Ganeshrao Peta, Kothapeta, Guntur, Andhra Pradesh 522001",
        "contactNumber":08632219955,
    },
    {
        "bloodBankName":"Rotary Red Cross Blood Bank",
        "district":"Krishna",
        "Address":"26-5-5, G S Raju Rd, Gandhi Nagar, Vijayawada, Andhra Pradesh 520003",
        "contactNumber":08662570082,
    },
    {
        "bloodBankName":"Suraksha Voluntary Blood Bank",
        "district":"Krishna",
        "Address":"29-10-8, Govinda Rajulu Naidu St, Suryaraopeta, Governor Peta, Vijayawada, Andhra Pradesh 520002",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Vijaya Sri Blood Bank",
        "district":"Krishna",
        "Address":"#29-19-27 opp :andhra bank &HDFC bank ATMS, Dornakal Rd, Suryaraopeta, Andhra Pradesh 520002",
        "contactNumber":08666663827,
    },
    {
        "bloodBankName":"Blood Bank",
        "district":"Krishna",
        "Address":"Andhra Hospital, Prakasam Rd, Governor Peta, Vijayawada, Andhra Pradesh 520003",
        "contactNumber":08662573636,
    },
    {
        "bloodBankName":"Chaitanya Blood Bank with Components",
        "district":"Krishna",
        "Address":"1st floor, Vasavya Complex, Benz Cir, Gurunanak Nagar, K P Nagar, Vasavya Nagar, Vijayawada, Andhra Pradesh 520010",
        "contactNumber":08662497977,
    },
    {
        "bloodBankName":"Sai Krishna Clinical labs",
        "district":"Krishna",
        "Address":" Vangaveeti Mohan Ranga Rd, Ramkingesh Nagar, Krishna Nagar, Vijayawada, Andhra Pradesh 520010",
        "contactNumber":09397889945,
    },
    {
        "bloodBankName":"Gudivada Blood Bank",
        "district":"Krishna",
        "Address":"Satyanarayana Puram, Gudivada, Andhra Pradesh 521301",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Lions District 316D Blood Bank",
        "district":"Krishna",
        "Address":"Shop No. 29-4, Sowbhagya Apartment, 54E, Prakasam Rd, Governor Peta, Vijayawada, Andhra Pradesh 520002",
        "contactNumber":08662573636,
    },
    {
        "bloodBankName":"Nagarjuna Blood Bank",
        "district":"Krishna",
        "Address":"No 8-102, Panta Kaluva Rd, New Postal Colony-2, Ramachandra Nagar, Kanuru, Vijayawada, Andhra Pradesh 520007",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Vijayshree Blood Bank",
        "district":"Krishna",
        "Address":"23-27-23, Rp Street, Seetharampuram, Seetharampuram, Vijayawada, Andhra Pradesh 520011",
        "contactNumber":08662433199,
    },
    {
        "bloodBankName":"Area Hospital Blood Bank",
        "district":"Krishna",
        "Address":"Machilipatnam Nuzvid Kalluru Rd, Gowri Sankar Puram, Nagavarappadu, Gudivada, Andhra Pradesh 521301",
        "contactNumber":08674245040,
    },
    {
        "bloodBankName":"Suraksha Blood Bank with Components",
        "district":"Krishna",
        "Address":"#29-8-1A, Nakkala Rd, Suryaraopeta, Vijayawada, Andhra Pradesh 520002",
        "contactNumber":08662434499,
    },
    {
        "bloodBankName":"sai krishna Clinical labs",
        "district":"Krishna",
        "Address":"#41-29/2-64,ranigari thota, krishnalanka, vijayawada, Vijayawada, Andhra Pradesh 520013",
        "contactNumber":09397889945,
    },
    {
        "bloodBankName":"Srinivasa Laboratory & Blood Bank",
        "district":"Krishna",
        "Address":"R C R Road, Suryaraopeth, Suryaraopeth, opposite St To Vijaya Talkies, Vijayawada, Andhra Pradesh 520002",
        "contactNumber":08662439523,
    },
    {
        "bloodBankName":"Saint Ann's Hospital Blood Bank",
        "district":"Krishna",
        "Address":"American Hospital Rd, Punammathota, Labbipet, Vijayawada, Andhra Pradesh 520002",
        "contactNumber":08662572057,
    },
    {
        "bloodBankName":"Viswa Bharathi Super Speciality Hospital",
        "district":"Kurnool",
        "Address":"1st Floor, O.P.Block, Gayathry Estate, Kurnool, Andhra Pradesh 518002",
        "contactNumber":08518229294,
    },
    {
        "bloodBankName":"M/S. Viswa Bharathi Blood Bank",
        "district":"Kurnool",
        "Address":"Palakottalu, Gayathree Estates, Deva Nagar, Kurnool, Andhra Pradesh 518002",
        "contactNumber":08518222940,
    },
    {
        "bloodBankName":"New Srikakulam Blood Bank",
        "district":"Srikakulam",
        "Address":"Door # 04-01-139/1, 1st Floor, Palakonda Road, Srikakulam - 532001, Day & Night Junction",
        "contactNumber":9550501503,
    },
    {
        "bloodBankName":"Indian Red Cross Society (Blood Bank)",
        "district":"Srikakulam",
        "Address":"Palakonda Road, Srikakulam Ho, Srikakulam - 532001, Behind Two Town Police Station",
        "contactNumber":7386907041,
    },
    {
        "bloodBankName":"Red Cross Blood Bank",
        "district":"Srikakulam",
        "Address":"Petromax St, Head Post Office Area, Ranasthali, New Colony, Palakonda, Srikakulam - 532440, Near Bapuji Kalamandir, Opp DM&HO Office",
        "contactNumber":8942226555,
    },
    {
        "bloodBankName":"Lions Blood Bank",
        "district":"Srikakulam",
        "Address":"Door 2115/2 1st Floor Rims Hospital Junction, Balaga, Palakonda Road, Srikakulam - 532001",
        "contactNumber":8942279666,
    },
    {
        "bloodBankName":"Rims Blood Bank",
        "district":"Srikakulam",
        "Address":"Srikakulam Ho, Srikakulam - 532001,",
        "contactNumber":9000273960,
    },
    {
        "bloodBankName":"Area Hospital Blood Bank",
        "district":"Srikakulam",
        "Address":"Pathapatnam, Srikakulam - 532213",
        "contactNumber":9948765449,
    },
    {
        "bloodBankName":"M/S. APVVP Area Hospital Blood Bank",
        "district":"Nellore",
        "Address":"Vaddi Palem, Kavali, Andhra Pradesh 524201",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Narayana Medical College & Hospital Blood Bank",
        "district":"Nellore",
        "Address":" Nellore, Andhra Pradesh 524003",
        "contactNumber":08612317963,
    },
    {
        "bloodBankName":"Government Hospital Blood Bank",
        "district":"Nellore",
        "Address":"Puritipalem, Gudur, Andhra Pradesh 524101",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Rotary Blood Bank",
        "district":"Vishakapatnam",
        "Address":"Jagadamba Junction,Maharanipeta, Maharanipeta, near Makka Masjid, Visakhapatnam, Andhra Pradesh 530002",
        "contactNumber":08912506678,
    },
    {
        "bloodBankName":"Blood Bank, KGH",
        "district":"Vishakapatnam",
        "Address":"Maharani Peta, Visakhapatnam, Andhra Pradesh 530002",
        "contactNumber":null,
    },
    {
        "bloodBankName":"R C Bothra Voluntary Blood Bank",
        "district":"Vishakapatnam",
        "Address":"D No 48-6-33, Ramatalkies Junction, Srinagar, Srinagar, Visakhapatnam, Andhra Pradesh 530016",
        "contactNumber":08916453360,
    },
    {
        "bloodBankName":"Visakha Voluntary Blood Bank",
        "district":"Vishakapatnam",
        "Address":"D No 10-2-1/1, 1st Floor, Krishna Arcade, Old Gajuwaka Junction, Old Gajuwaka Junction, Visakhapatnam, Andhra Pradesh 530026",
        "contactNumber":08912531553,
    },
    {
        "bloodBankName":"A. S. Raja Voluntary Blood Bank",
        "district":"Vishakapatnam",
        "Address":"10, 50-11/5, Waltair Main Rd, Beside Care Hospital, Ram Nagar, Visakhapatnam, Andhra Pradesh 530002",
        "contactNumber":09966607537,
    },
    {
        "bloodBankName":"Sanjeevani Voluntary Blood Bank",
        "district":"Vishakapatnam",
        "Address":"26-50, 16/4, Kanithi Rd, Chaitanya Nagar, Gajuwaka, Visakhapatnam, Andhra Pradesh 530026",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Life Share Blood Bank",
        "district":"Vishakapatnam",
        "Address":"Land Mark Towers, 4th Floor, Asilmetta, Visakhapatnam, Andhra Pradesh 530003",
        "contactNumber":null,
    },
    {
        "bloodBankName":"NTR TRUST BLOOD BANK",
        "district":"Vishakapatnam",
        "Address":"10 Waltair Main Road TPT, Nehru Nagar TPT/VUDA Colony, Nehru Nagar, Ram Nagar, Visakhapatnam, Andhra Pradesh 530002",
        "contactNumber":08912565858,
    },
    {
        "bloodBankName":"Life Share BLOOD BANK",
        "district":"Vishakapatnam",
        "Address":"near, Sampath Vinayaka Temple Rd, opp Kalyan jewelrys, Opposite Hotel Meghalaya, Ram Nagar, Visakhapatnam, Andhra Pradesh 530002",
        "contactNumber":09989558350,
    },
    {
        "bloodBankName":"Indian Red Cross Society",
        "district":"Vishakapatnam",
        "Address":"14-35-4 Opp Zilla Parshad, Maharani Peta, Visakhapatnam, Andhra Pradesh 530002",
        "contactNumber":08912703953,
    },
    {
        "bloodBankName":"M/S. Government Victoria Hospital Blood Bank",
        "district":"Vishakapatnam",
        "Address":"One Town, Port Area, Visakhapatnam, Andhra Pradesh 530001",
        "contactNumber":null,
    },
    {
        "bloodBankName":"M/S. Visakha Steel General Hospital Blood Bank",
        "district":"Vishakapatnam",
        "Address":"Sector 6, Gajuwaka, Visakhapatnam, Andhra Pradesh 530032",
        "contactNumber":08912887722,
    },
    {
        "bloodBankName":"M/S. Gitam Institute Of Medical Sciences And Research Blood Bank",
        "district":"Vishakapatnam",
        "Address":"Rushikonda, Visakhapatnam, Andhra Pradesh 530045",
        "contactNumber":08912524777,
    },
    {
        "bloodBankName":"Blood Bank Centre - Indian Red Cross Society",
        "district":"Vizianagaram",
        "Address":"Near;Ganesh Temple Junction, Contonment, Vizianagaram Cantonment, Vizianagaram, Andhra Pradesh 535002",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Vijaya blood bank",
        "district":"Vizianagaram",
        "Address":"D.no:18-01-18, 3rd floor, Zidduvari St, Vizianagaram, Andhra Pradesh 535001",
        "contactNumber":null,
    },
    {
        "bloodBankName":"NVN Blood Bank",
        "district":"Vizianagaram",
        "Address":"2nd Floor, Matam Street, Gumchi Junction, Vizianagaram, Andhra Pradesh 535002",
        "contactNumber":08922279111,
    },
    {
        "bloodBankName":"Rotary Blood Bank",
        "district":"Vizianagaram",
        "Address":"NCS Rd, near District Labour office, Kothagraharam, Chinna Veedhi, Balaji Nagar, Vizianagaram, Andhra Pradesh 535001",
        "contactNumber":null,
    },
    {
        "bloodBankName":"GMR Varalakshmi Care Hospital Blood Bank",
        "district":"Vizianagaram",
        "Address":"Razam, Andhra Pradesh 532127",
        "contactNumber":08941253183,
    },
    {
        "bloodBankName":"Indian Red Cross Society",
        "district":"Vizianagaram",
        "Address":"Collector Office Junction, Contonment Area, Vizianagaram, Andhra Pradesh 535003",
        "contactNumber":08978277339,
    },
    {
        "bloodBankName":"Indian Red Cross Society Blood Bank, RCH-II",
        "district":"Vizianagaram",
        "Address":"Parvathipuram, Andhra Pradesh 535501",
        "contactNumber":08963222088,
    },
    {
        "bloodBankName":"M/S. Anil Neerukonda Hospital Blood Bank",
        "district":"Vizianagaram",
        "Address":"M, Sanghivalasa, Bheemunipatnam, Andhra Pradesh 531162",
        "contactNumber":08912821111,
    },
    {
        "bloodBankName":"Rayagada Blood Bank",
        "district":"Vizianagaram",
        "Address":"Blood Bank Officer, Red Cross Blood Bank, DHH, Odisha 765001",
        "contactNumber":6856236465,
    },
    {
        "bloodBankName":"R C Bothra Voluntary Blood Bank",
        "district":"Vizianagaram",
        "Address":"D No 48-6-33, Ramatalkies Junction, Srinagar, Srinagar, Visakhapatnam, Andhra Pradesh 530016",
        "contactNumber":08916453360,
    },
    {
        "bloodBankName":"A. S. Raja Voluntary Blood Bank",
        "district":"Vizianagaram",
        "Address":"A. S. Raja Voluntary Blood Bank",
        "contactNumber":09966607537,
    },
    {
        "bloodBankName":"Buddala Blood Bank",
        "district":"West Godavari",
        "Address":"Venkatarayapuram, Tanuku, Andhra Pradesh 534211",
        "contactNumber":08819227582,
    },
    {
        "bloodBankName":"Eluru Voluntary Blood Bank",
        "district":"West Godavari",
        "Address":"Ramachandra Rao Pet, Eluru, Andhra Pradesh 534006",
        "contactNumber":null,
    },
    {
        "bloodBankName":"RED CROSS BLOODBANK",
        "district":"West Godavari",
        "Address":"AP Housing Board Colony, Narsapur, Andhra Pradesh 534275",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Jangareddygudem blood bank",
        "district":"West Godavari",
        "Address":"Rajana ramulu complex First floor ,Chintal Road, Jangareddigudem, Andhra Pradesh 534447",
        "contactNumber":null,
    },
    {
        "bloodBankName":"ASN Raju Charitable Trust Blood Bank",
        "district":"West Godavari",
        "Address":"RK Plaza, Juvvalapalem Rd, Sri Rama Puram, Bhimavaram, Andhra Pradesh 534202",
        "contactNumber":09951225559,
    },
    {
        "bloodBankName":"Ananda Blood Bank",
        "district":"West Godavari",
        "Address":"Sivaraopeta Road, Door No 27-8-21, 3, Bhimavaram, Andhra Pradesh 534202",
        "contactNumber":08816230888,
    },
    {
        "bloodBankName":"M/S. Government Headquarters Hospital Blood Bank",
        "district":"West Godavari",
        "Address":"Ramachandra Rao Pet, Eluru, Andhra Pradesh 534006",
        "contactNumber":08812220333,
    },
    {
        "bloodBankName":"M/S. Indian Red Cross Society Blood Bank Jangareddi Gudem",
        "district":"West Godavari",
        "Address":"Jangareddigudem, Andhra Pradesh 534447",
        "contactNumber":08821225305,
    },
    {
        "bloodBankName":"Dhanwantari Voluntary Blood Bank & Blood Components",
        "district":"West Godavari",
        "Address":"D.No 46, 21-1, Manasa Hospital Rd, Near China Anjaneyaswamy Temple, Danavai Peta, Rajahmundry, Andhra Pradesh 533103",
        "contactNumber":08832473050,
    },
    {
        "bloodBankName":"Vijayasri Blood Bank",
        "district":"West Godavari",
        "Address":"Behind Gandhi Park, Danavai Peta, Rajahmundry, Andhra Pradesh 533103",
        "contactNumber":08832555199,
    },
    {
        "bloodBankName":"Uddaraju Ananda Raju Foundation",
        "district":"West Godavari",
        "Address":"27-8-21/3, Juvvalapalem Rd, Balusumoodi, Bhimavaram, Andhra Pradesh 534202",
        "contactNumber":08816272507,
    },
    {
        "bloodBankName":"Dr. Mulla Pudi Harishchandra Prasad Red Cross Blood Bank",
        "district":"West Godavari",
        "Address":"Sajjapuram, Tanuku, Andhra Pradesh 534211",
        "contactNumber":08819221184,
    },
    {
        "bloodBankName":"SRI BUDDALA NARASIMHA MURTY VOLUNTARY BLOOD BANK",
        "district":"West Godavari",
        "Address":"Blood Bank, Tanuku, Andhra Pradesh",
        "contactNumber":09949601513,
    },
    {
        "bloodBankName":"Vani Cooperative Urban Bank Limited",
        "district":"West Godavari",
        "Address":"35-32-2, AB Bhavan, Yanamandra, Seeni Vari St, Venkatarayapuram, Tanuku, Andhra Pradesh 534211",
        "contactNumber":08819226235,
    },
    {
        "bloodBankName":"Suraksha Voluntary Blood Bank",
        "district":"West Godavari",
        "Address":"22/148, first floor, Gandhi Rd, vasanta Peta, Proddatur, 516360",
        "contactNumber":08564257444,
    },

]

exports.data2=data2;