const ArrayData =[
    {
    "bloodBankName":"Deepu blood bank",
    "district":"Anantapur",
    "Address":"2nd Cross Rd,Central Exchange colony,Ashok Nagar,Anantapur,Anantapur,Andhra Pradesh 515001",
    "contactNumber":08554246933,
    },
    {
    "bloodBankName":"Red Cross Blood Bank",
    "district":"Anantapur",
    "Address":"JNTU College Of Engineering, Anantapur, Andhra Pradesh 515002",
    "contactNumber":null,
    },
    {
    "bloodBankName":"Chaitanya Blood Bank",
    "district":"Anantapur",
    "Address":"Sai Nagar, Anantapur, Andhra Pradesh 515001",
    "contactNumber":null,
    },
    {
    "bloodBankName":"Rural Development Trust Hospital Blood Bank",
    "district":"Anantapur",
    "Address":"Krishnagiri, Road, Veradapuram, Bathalapalli, Andhra Pradesh 515661",
    "contactNumber":08559244259,
    },
    {
        "bloodBankName":"Indian Red Cross Society Blood Bank, District Branch",
        "district":"Anantapur",
        "Address":"near JNTU Engeneering College, Shantha Pet, Sharada Nagar, Anantapur, Andhra Pradesh 515001",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Andhra Pradesh Vaidya Vidhana Parishad Area Hospital - IRCS Blood Bank",
        "district":"Kadapa",
        "Address":"APVVP BLOOD BANK, Kacheri St, Pulivendula, Andhra Pradesh 516390",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Government General Hospital Blood Bank",
        "district":"Anantapur",
        "Address":"Sharada Nagar, Anantapur, Andhra Pradesh 515001",
        "contactNumber":08554275024,
    },
    {
        "bloodBankName":"S. S. S. I. H. M. S. Blood Bank",
        "district":"Anantapur",
        "Address":" Puttaparthi Main Rd, Prasanthigram, Puttaparthi, Andhra Pradesh 515134",
        "contactNumber":08555287900,
    },
    {
        "bloodBankName":"Indian Red Cross Society",
        "district":"Anantapur",
        "Address":"Blood Bank Medical Officer, Blood Bankn Red Cross Society, Anantpur, Anantapur, Andhra Pradesh 515001",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Bruhada Blood Bank",
        "district":"Kadapa",
        "Address":"21-648-1, 2nd & 3rd Floor, Prasad Towers, Old Municipal Office Road, Kadapa, Andhra Pradesh 516001",
        "contactNumber":08562225535,
    },
    {
        "bloodBankName":"Indian Red Cross Society Blood Bank",
        "district":"Kadapa",
        "Address":"Ganagapeta, Kadapa, Andhra Pradesh 516001",
        "contactNumber":08562272829,
    },
    {
        "bloodBankName":"Vijaya Blood Bank",
        "district":"Kurnool",
        "Address":"Srinivasa Nagar, Nandyala, Andhra Pradesh 518501",
        "contactNumber":09491247878,
    },
    {
        "bloodBankName":"RIMS BLOOD BANK",
        "district":"Kadapa",
        "Address":"Puttampalli, Andhra Pradesh 516002",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Andhra Pradesh Vaidya Vidhana Parishad Area Hospital - IRCS Blood Bank",
        "district":"Kadapa",
        "Address":"Government Hospital, Yerraguntla Rd, Dastagiripet 2, Nadimpalli, Proddatur, Andhra Pradesh 516360",
        "contactNumber":null,
    },
    {
        "bloodBankName":"Akshaya Blood Bank",
        "district":"Kurnool",
        "Address":"Opp. Gopal Hospital, Budhwar Pet, Kurnool, Andhra Pradesh 518002",
        "contactNumber":08518255573,
    },
    {
        "bloodBankName":"RAKSHANA BLOOD BANK",
        "district":"Chittoor",
        "Address":"18-1-505c, VV Mahal Rd, Reddy and Reddy's Colony, Tirupati, Andhra Pradesh 517501",
        "contactNumber":08772223622,   
    },
    {
        "bloodBankName":"SVSCT Blood Bank",
        "district":"Chittoor",
        "Address":"10-3-206, M4, 1st Floor, Reddy & Reddy Colony, Tirupati, Andhra Pradesh 517501",
        "contactNumber":08776667671,
    },
    {
        "bloodBankName":"Blood Bank, Kadiri",
        "district":"Anantapur",
        "Address":"Revenue Colony, Kadiri, Andhra Pradesh 515591",
        "contactNumber":08494221544,
    },
    {
        "bloodBankName":"Indian Red Cross Society Blood Bank",
        "district":"Anantapur",
        "Address":"Mukkidipeta, Hindupuram, Andhra Pradesh 515201",
        "contactNumber":08556225900,
    },
    {
        "bloodBankName":"Indian Red Cross Society Blood Bank",
        "district":"Kurnool",
        "Address":"NH 18, Alluri Sitarama Raju Nagar, Kurnool, Andhra Pradesh 518002",
        "contactNumber":null,
    },
    {
        "bloodBankName":"BLOOD 2 LIVE",
        "district":"Kadapa",
        "Address":"1st Floor, Upstair, C.R.I Subba reddy complex, Vijaya Durga Colony Rd, Near built up, Kadapa, Andhra Pradesh 516001",
        "contactNumber": 08885858591,
    },
    {
        "bloodBankName":"Indian Red Cross Society Blood Bank",
        "district":"Prakasham",
        "Address":"Santhapet, Ongole, Andhra Pradesh 523001",
        "contactNumber": null, 
    },
    {
        "bloodBankName":"Nellore Blood Bank",
        "district":"Nellore",
        "Address":"2nd Floor, Up Stair Andhra Bank, Brindavanam Road, Nellore, Andhra Pradesh 524001",
        "contactNumber": 08612348377, 
    },
    {
        "bloodBankName":"RAKSHANA BLOOD BANK",
        "district":"Chittoor",
        "Address":"opp. v.v.mahal road, Srinivasa Nagar, Sarojini Devi Layout, Tirupati, Andhra Pradesh 517501",
        "contactNumber": null, 
    },
    {
        "bloodBankName":"SVIMS Blood Bank",
        "district":"Chittoor",
        "Address":"Sri Padmavati Mahila Visvavidyalayam, Tirupati, Andhra Pradesh 517507",
        "contactNumber": null,   
    },
    {
        "bloodBankName":"Model Blood Bank Tpt",
        "district":"Chittoor",
        "Address":"SVRR Govt general Hospital, Tirupathi, Andhra Pradesh 517501",
        "contactNumber": 09849099750,    
    },
    {
        "bloodBankName":"Life Line Voluntary Blood Bank",
        "district":"Prakasham",
        "Address":"Door No. 37-1- 169/54, 2nd Floor, Sai Vijaya Diagnostic Centre Sundaraiaha Bhavan Road, Ongole, Andhra Pradesh 523002",
        "contactNumber": 09247023117, 
    },
    {
        "bloodBankName":"vijayasri blood bank",
        "district":"Nellore",
        "Address":"Gandhinagar, Pogathota, Nellore, Andhra Pradesh 524001",
        "contactNumber": 09701233199,
    },
    {
        "bloodBankName":"Aapadbandhu Blood Bank",
        "district":"Guntur",
        "Address":"D.No. 27- 172, 1st Floor Lawyer Street, Dist A P, Kothapeta, Vinukonda, Andhra Pradesh 522647",
        "contactNumber": null,  
    },
    {
        "bloodBankName":"South Central Railway Hospital Blood Bank",
        "district":"Anantapur",
        "Address":" Aravinda Nagar, Guntakal, Andhra Pradesh 515801",
        "contactNumber": 08552227166, 
    },
    {
        "bloodBankName":"Blood Bank",
        "district":"Prakasham",
        "Address":"Brundavan Nagar, Pandaripuram, Ongole, Andhra Pradesh 523001",
        "contactNumber": null, 
    },
    {
        "bloodBankName":"Palnadu Blood Bank",
        "district":"Guntur",
        "Address":"hospitals Chilakaluripet Road opp:mahatma gandhi hospital upstair:lakshmi, Guntur, Andhra Pradesh",
        "contactNumber": null,  
    },
    {
        "bloodBankName":"VIJAYASREE BLOOD BANK",
        "district":"Prakasham",
        "Address":"523001, Brundavan Nagar, Pandaripuram, Ongole, Andhra Pradesh 523001",
        "contactNumber": 09985833199,
    },
    {
        "bloodBankName":"Simhapuri Voluntary Blood Bank",
        "district":"Nellore",
        "Address":"H.No:16-2/126, Above Ravi Diabetics Centre 2nd & 3rd Floor,, Beside Rich Hospital, Railway Track Road, Pogathota, Nellore, Andhra Pradesh 524001",
        "contactNumber": 08612341667,
    },
    {
        "bloodBankName":"Navya Blood Bank",
        "district":"Prakasham",
        "Address":"Opp. RTC Bus Stand, Venkateswara Complex, Venkateswara Nagar, Venkata Ramana Hospital Compound, Ongole, Andhra Pradesh 523001",
        "contactNumber": 09966344449,
    },
    {
        "bloodBankName":"Palnadu Blood Bank",
        "district":"Guntur",
        "Address":"Upstair:lakshmi Hospital,opp:mahatma Gandhi Hospital, Narasaraopeta, Andhra Pradesh",
        "contactNumber":9701324393,  
    },
    {
        "bloodBankName":"Indian Red Cross Society Blood Bank, Chittoor",
        "district":"Chittoor",
        "Address":"District Govt. Head Quarters Hospital Campus, Andhra Pradesh",
        "contactNumber": null,  
    },
    {
        "bloodBankName":"NRT Blood Bank",
        "district":"Guntur",
        "Address":"Guntur, SH-45, Piduguralla Narasaraopet Road, Narasaraopet 522301, Arundelpet, Narasaraopeta, Andhra Pradesh 522601",
        "contactNumber": 09542628888,  
    },
    {
        "bloodBankName":"District Hospital Blood Bank",
        "district":"Kurnool",
        "Address":"Government Hospital, Sadiq Nagar, Nandyala, Andhra Pradesh 518502",
        "contactNumber": null,  
    },
    {
        "bloodBankName":"Aapadbandhu Blood bank",
        "district":"Prakasham",
        "Address":"D. No-21-1-190, 1st floor, above KVB bank GBC Road, opp nerella buildings, Chirala, Andhra Pradesh 523155",
        "contactNumber": 09494647744,  
    },
    {
        "bloodBankName":"Indian Red Cross Society",
        "district":"Nellore",
        "Address":"Somasekara Puram, Nellore, Andhra Pradesh 524003",
        "contactNumber": 08612320470,
    },
    {
        "bloodBankName":"Indian Red Cross Society",
        "district":"Nellore",
        "Address":"R.D.O Office, compound, Kacherimitta, Kavali, Andhra Pradesh 524201",
        "contactNumber": null,  
    },
    {
        "bloodBankName":"KIMS HOSPITAL BLOOD BANK,ONGOLE",
        "district":"Prakasham",
        "Address":"Muktinuthala padu,Near Agriculture Market community Hall, Ongole, Andhra Pradesh 523001",
        "contactNumber": null, 
    },
    {
        "bloodBankName":"SVRRGGH - Model Blood Bank",
        "district":"Chittoor",
        "Address":"Alipiri Rd, Srinivasa Nagar, SVRRGGH, TIRUPATI, Tirupati, Andhra Pradesh 517501",
        "contactNumber": 08772286290,
    },
    {
        "bloodBankName":"Indian Red Cross Society Blood Bank",
        "district":"Prakasham",
        "Address":"Old Government Hospital, Shivaji Nagar, Markapur, Andhra Pradesh 523316",
        "contactNumber": 08596223485,
    },
    {
        "bloodBankName":"Khoon Ka Rishta Blood Donors Association Office",
        "district":"Kadapa",
        "Address":"#20/1184-1-4, Room No: 4, 1st Floor, Wakf Board Complex Krishna Circle, Madras Rd, Kadapa, Andhra Pradesh 516001",
        "contactNumber": 09948104130,
    },
    {
        "bloodBankName":"Emergency & Bloodbank",
        "district":"Chittoor",
        "Address":"Open Air Auditorium - S V Medical College, Alipiri Rd, Alipiri Gate, Sri Padmavati Mahila Visvavidyalayam, Tirupati, Andhra Pradesh 517507",
        "contactNumber": null,
    },
    {
        "bloodBankName":"New Vision Blood Bank",
        "district":"Prakasham",
        "Address":"Nellore Bus Stand Center, Bhagyanagar, Ongole, Andhra Pradesh 523001",
        "contactNumber": null,
    },
    {
        "bloodBankName":"RIMS BLOOD BANK",
        "district":"Prakasham",
        "Address":"Ramnagar, Ongole, Andhra Pradesh 523001",
        "contactNumber": null,
    },
    {
        "bloodBankName":"Nrt Blood Bank",
        "district":"Guntur",
        "Address":"Gbr Super Speciality Hospital, 10-1, 10 1, Palnadu Rd, Narasaraopeta, Andhra Pradesh 522601",
        "contactNumber": null,
    },
    {
        "bloodBankName":"Boga Parvathamma Rakthadaana Seva Samiti ",
        "district":"Kadapa",
        "Address":"Jaya Nagar Colony, N.G.O Colony, Kadapa, Andhra Pradesh 516002",
        "contactNumber": 09440269795,
    },
    {
        "bloodBankName":"Anjireddy Multi Specialty Blood Bank",
        "district":"Guntur",
        "Address":" Dr Anji Reddy Multispeciality Hospitals Pvt Ltd, Piduguralla - Govindapuram Rd, Centripalem, Piduguralla, Andhra Pradesh 522413",
        "contactNumber": 08649254567,
    },
    {
        "bloodBankName":"NTR TRUST BLOOD BANK",
        "district":"Chittoor",
        "Address":"#10-3-203C, Kotakommala Street, Tirupati, Andhra Pradesh 517501",
        "contactNumber": 08772255668,
    },
    {
        "bloodBankName":"Aswini Hospital Blood Bank, TTD",
        "district":"Chittoor",
        "Address":"Devastanam (TTD, Tirumala, Tirupati, Andhra Pradesh 517507",
        "contactNumber": null, 
    },
    {
        "bloodBankName":"M/S. Rims General Hospital Blood Bank",
        "district":"Prakasham",
        "Address":"5th Ln, Dharavari Thota, Bhagyanagar, Ongole, Andhra Pradesh 523001",
        "contactNumber": null, 
    },
    {
        "bloodBankName":"Indian Red Cross Society Blood Bank Narasaraopet",
        "district":"Guntur",
        "Address":"National Highway 167A, Balayyanagar, Narasaraopeta, Andhra Pradesh 522601",
        "contactNumber": null,  
    },
    {
        "bloodBankName":"Dharmavaram Co Op Town Bank",
        "district":"Anantapur",
        "Address":"Door No 20/61, Kota, Brahmin St, Akkpedianera, Dharmavaram, Andhra Pradesh 515671",
        "contactNumber": 08559223038, 
    },
    {
        "bloodBankName":"Prakasam blood donors",
        "district":"Prakasham",
        "Address":"Dasari St, Podili, Andhra Pradesh 523240",
        "contactNumber": null,  
    },
    {
        "bloodBankName":"SVS charitable Trust BLOOD BANK, (SVSCT)Blood Bank ,1st Floor ",
        "district":"Chittoor",
        "Address":"Reddy & Reddy's Colony, Reddy and Reddy's Colony, Tirupati, Andhra Pradesh 517501",
        "contactNumber": 08776667671, 
    },
    {
        "bloodBankName":"Nova Blood Bank Nellore",
        "district":"Nellore",
        "Address":"Gandhinagar, Pogathota, Nellore, Andhra Pradesh 524001",
        "contactNumber": null,
    },
    {
        "bloodBankName":"Indian Red Cross Society, Madanapalli RCH - II",
        "district":"Chittoor",
        "Address":"Neerugattupalle, Madanapalle, Andhra Pradesh 517325",
        "contactNumber": 08571222087,
    },
    {
        "bloodBankName":"Indian Red Cross Society",
        "district":"Kurnool",
        "Address":" 50/74/12, Alluri Sitarama Raju Nagar, Kurnool, Andhra Pradesh 518002",
        "contactNumber": 08518255342,
    },
    {
        "bloodBankName":"RCH -II Blood Bank, Area Hospital, Adoni",
        "district":"Kurnool",
        "Address":"Old Town, Adoni, Andhra Pradesh 518301",
        "contactNumber": null, 
    },
    {
        "bloodBankName":"sri gnana saraswathidevi charitable trust",
        "district":"Kadapa",
        "Address":"Badvel Road, Porumamilla, Andhra Pradesh 516193",
        "contactNumber": 09010526926,
    },
    {
        "bloodBankName":"M/S. R. R. Hospital Blood Bank",
        "district":"Kurnool",
        "Address":"Narasimha reddy Nagar, River View Colony, Kurnool, Andhra Pradesh 518004",
        "contactNumber": 08518223131,
    },
    {
        "bloodBankName":"City Diagnostic Center",
        "district":"Prakasham",
        "Address":"Nataraj St, 1, Giddalur, Andhra Pradesh 523357",
        "contactNumber": 08405242056,
    },
    {
        "bloodBankName":"Dr. Venkat Diagnostic Lab",
        "district":"Anantapur",
        "Address":"Kamalanagar, Anantapur, Andhra Pradesh 515001",
        "contactNumber": 08554249930,
    },
    {
        "bloodBankName":"Life Care diagnostic Lab",
        "district":"Anantapur",
        "Address":" life care lab, opposite to old Andhrapragathi gramina bank Kokkanti cross, Andhra Pradesh 515571",
        "contactNumber": 09492082604,
    },
    {
        "bloodBankName":"Life Care diagnostic Lab",
        "district":"Anantapur",
        "Address":" life care lab, opposite to old Andhrapragathi gramina bank Kokkanti cross, Andhra Pradesh 515571",
        "contactNumber": 09492082604,
    },
]

exports.ArrayData = ArrayData;